# Generated by Django 4.2.7 on 2023-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_remove_provider_has_flat_price_remove_provider_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='texto',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
