# Generated by Django 4.2.7 on 2023-11-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_comentario_data_investment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
