# Generated by Django 4.2.7 on 2023-11-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
